### ISSUE TITLE
Require preprocessors to continue working on models

### ISSUE THREAD

**Issue by charlesxch** [UBC-MDS/Group_7_Project#54]
Hi Gretel, @gtmx23. Did you finish the preprocessor scripts. I need the preprocessor to start working on the model scritps. Please let me know once you finish it.

**Comment by gtmx23** [comment]
Hi, I forgot to submit a pull request but just submitted one! There seem to be conflicts in the environment file though. Was studying for stats but will test the pickle object after the quiz!

**Comment by gtmx23** [comment]
<img width="801" alt="image" src="https://github.com/UBC-MDS/Group_7_Project/assets/143576628/92393bbc-d002-4034-9dd3-eb342998c6b7">
I think it is working!

**Comment by gtmx23** [comment]
<img width="972" alt="image" src="https://github.com/UBC-MDS/Group_7_Project/assets/143576628/138c9e1f-141b-4120-870d-fec84957c70d">
I need approval to merge though haha

**Comment by riyaeliza123** [comment]
@gtmx23 accepted you pr

**Comment by gtmx23** [comment]
Thank you Riya!
